// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGwQ8tVPiCNmL1VErOrW9ae4eddHQthM4',
    appId: '1:186875538514:web:ca1a7bf9510bc9fbd2438b',
    messagingSenderId: '186875538514',
    projectId: 'flutterchatapp-5662e',
    authDomain: 'flutterchatapp-5662e.firebaseapp.com',
    storageBucket: 'flutterchatapp-5662e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjJNgOjVzPerQJpcRj5VvfrD8xTniOFio',
    appId: '1:186875538514:android:11848c45ffba6863d2438b',
    messagingSenderId: '186875538514',
    projectId: 'flutterchatapp-5662e',
    storageBucket: 'flutterchatapp-5662e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVvp1JHanDTTGgjKudGdnHbsIxQU0Qws0',
    appId: '1:186875538514:ios:70547af971bdaa37d2438b',
    messagingSenderId: '186875538514',
    projectId: 'flutterchatapp-5662e',
    storageBucket: 'flutterchatapp-5662e.appspot.com',
    iosClientId: '186875538514-6gmglrq1n7g9d5qmbci4qbbj48o62c6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListAndroidIos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVvp1JHanDTTGgjKudGdnHbsIxQU0Qws0',
    appId: '1:186875538514:ios:70547af971bdaa37d2438b',
    messagingSenderId: '186875538514',
    projectId: 'flutterchatapp-5662e',
    storageBucket: 'flutterchatapp-5662e.appspot.com',
    iosClientId: '186875538514-6gmglrq1n7g9d5qmbci4qbbj48o62c6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListAndroidIos',
  );
}
